create database DEV_CRUD_APP_DATABASE;

--
-- TABLE: CRUD_APP_USER
--
CREATE TABLE public.CRUD_APP_USER
(
    ID_USER bigserial PRIMARY KEY NOT NULL,
    USERNAME_USER TEXT NOT NULL,
    PASSWORD_USER TEXT NOT NULL,
    LOGIN_COUNT_USER INT NOT NULL
);

--
-- TABLE: CRUD_APP_PERSON
--
CREATE TABLE public.CRUD_APP_PERSON
(
    ID_PERSON bigserial PRIMARY KEY NOT NULL,
    ID_USER INT,
    NAME_PERSON TEXT NOT NULL,
    AGE_PERSON INT NOT NULL,
    BIRTHDAY_PERSON TEXT NOT NULL,
    foreign key (ID_USER)
        references CRUD_APP_USER(ID_USER)
);

--
-- TABLE: CRUD_APP_ROLE
--
CREATE TABLE public.CRUD_APP_ROLE
(
    ID_ROLE BIGSERIAL PRIMARY KEY NOT NULL,
    NAME_ROLE TEXT NOT NULL,
    CODE_ROLE TEXT NOT NULL,
    DESCRIPTION_ROLE TEXT NOT NULL
);

--
-- TABLE: CRUD_APP_REL_USER_ROLE
--
CREATE TABLE public.CRUD_APP_REL_USER_ROLE
(
    ID_REL_USER_ROLE BIGSERIAL PRIMARY KEY NOT NULL,
    ID_USER INT NOT NULL,
    ID_ROLE INT NOT NULL,
    foreign key (ID_USER)
        references CRUD_APP_USER(ID_USER),
    foreign key (ID_ROLE)
        references CRUD_APP_ROLE(ID_ROLE)
);