create database DEV_CRUD_APP_DATABASE;

--
-- TABLE: CRUD_APP_PERSON
--
CREATE TABLE public.CRUD_APP_PERSON
(
    ID_PERSON SERIAL PRIMARY KEY NOT NULL,
    NAME_PERSON TEXT NOT NULL,
    AGE_PERSON INT NOT NULL,
    BIRTHDAY_PERSON TEXT NOT NULL
);

--
-- TABLE: CRUD_APP_USER
--
CREATE TABLE public.CRUD_APP_USER
(
    ID_USER SERIAL PRIMARY KEY NOT NULL,
    ID_PERSON INT NOT NULL,
    USERNAME_USER TEXT NOT NULL,
    PASSWORD_USER TEXT NOT NULL,
    LOGIN_COUNT_USER INT NOT NULL,
    FOREIGN KEY (ID_PERSON)
        REFERENCES CRUD_APP_PERSON(ID_PERSON)
);